version: "3"
services:
  mqtt5_db:
    image: eclipse-mosquitto
    container_name: mqtt5_web
    ports:
      - "1883:1883" # default mqtt port
      - "9001:9001" # default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - internal

  # MariaDB service
  mariadb:
    image: mariadb:latest
    container_name: mariadb_web
    environment:
      MYSQL_ROOT_PASSWORD: RootPwd
      MYSQL_DATABASE: mqttdata
      MYSQL_USER: mysqlUser
      MYSQL_PASSWORD: mysqlPwd
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: unless-stopped

  # Nginx webserver
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./nginx/data/:/var/www/html/
      - ./log/nginx:/var/log/nginx/

  # PHP-FPM service
  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./nginx/data/:/var/www/html/
      - ./log/php.log:/var/log/fpm-php.www.log

  # Python MQTT Listener service
  mqtt_listener:
    container_name: mqtt_listener
    build:
      context: .
      dockerfile: python/Dockerfile
    volumes:
      - ./python/scripts:/scripts
    working_dir: /scripts
    ports:
      - "5678:5678"
    depends_on:
      - mqtt5_db
      - mariadb
    environment:
      - MQTT_BROKER=mqtt5_web
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensor\data
      - MYSQL_HOST=mariadb_web
      - MYSQL_USER=mysqlUser
      - MYSQL_PASSWORD=mysqlPwd
      - MYSQL_DB=mqttdata
    networks:
      - internal

volumes:
  config:
  data:
  log:
  mariadb_data:

networks:
  internal:
    driver: bridge
  default:
    name: mqtt5-network
